# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
##########################################################################################  
### CONFIGURACION DE VARIABLES Y DATOS
##########################################################################################
locale                   : "es-ES"
title                    : "Droguier's Web"
title_separator          : "-"
name                     : &name "Daniel Andres Leiva"
description              : &description "Probando un nuevo bootstrap para Jekyll, version de implementación 2.0"
url                      : "" #http://droguier.me # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#enforce_ssl              : http://droguier.me
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "droguier"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"

### Social Sharing
twitter:
  username               : &twitter "echoes_daniel"
facebook:
  username               : #&facebook ""
  app_id                 :
  publisher              :
og_image                 : "site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/echoes_daniel"
    #- "https://facebook.com/michaelrose"

### Site Author
author:
  name             : *name
  avatar           : "echoes_perfil.jpg"
  bio              : "Estudiante de por vida."
  location         : "Santiago, Chile"
  email            : "daniel.leiva@ceinf.cl"
  uri              : "https://droguier.github.io/droguier.me/"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : *facebook
  foursquare       :
  github           : "droguier"
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : 5158839/daniel-leiva # http://stackoverflow.com/users/123456/username
  steam            : echoes_cs
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :

### Marcador dinamico
atom_feed:
  path                   : # blank (default) uses feed.xml

##########################################################################################  
### CONFIGURACION DE ARCHIVOS
##########################################################################################
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  #carpetas
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .bundle
  - .asset-cache
  - .jekyll-assets-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - vendor
  - tmp
  #archivos  
  - CNAME
  - Gemfile  
  - Rakefile
  - LICENSE
  - README  
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


##########################################################################################  
### CONFIGURACION DE ACCESO PAGINAS - LAYOUTS - SASS
##########################################################################################
# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _releases
  - scope:
      path: ""
      type: releases
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  releases:
    output: true
    permalink: /:collection/:path/


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Santiago # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


##########################################################################################  
### CONFIGURACION DE ELEMENTOS ADICIONALES [ICONOS , ELEMENTOS DE IMAGENES]
##########################################################################################
# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-83747666-1" # UA-2011187-3" -> Analytic for Minimal

#**************************************************
#**************************************************
### Configuracion estandar inicial
#title: mi titulo bonito
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
###
### Build settings
#markdown: kramdown
#theme: minima
#**************************************************
